const WHATSAPP='355692100222';
const img=p=>`/assets/${p}`;
const cats=[['iPhone','Latest Pro models, premium used and sealed stock'],['AirPods','Pro sound, ANC, Max and daily audio'],['MacBook','Air and Pro for work, study and creators'],['Watch','Ultra, Series and lifestyle tech']];
const gallery=['gallery/molla-real-1.jpg','gallery/molla-real-2.jpg','gallery/molla-real-3.jpg','gallery/molla-real-4.jpg','gallery/molla-real-5.jpg'];
const products=[
{id:1,cat:'iPhone',name:'iPhone 16 Pro Max',price:689,img:'products/real-product-1.jpg',desc:'Flagship iPhone experience with premium finish, Pro camera system and large display.',specs:['256GB','Titanium','Europe CE','Warranty'],badge:['BEST SELLER','PRO']},
{id:2,cat:'iPhone',name:'iPhone 15 Pro Max',price:589,img:'products/real-product-2.jpg',desc:'Premium Pro Max performance, excellent battery and cinematic camera quality.',specs:['256GB','Natural Titanium','Checked','Ready'],badge:['HOT DEAL','PRO MAX']},
{id:3,cat:'iPhone',name:'iPhone 14 Pro Max',price:449,img:'products/real-product-3.jpg',desc:'A strong premium choice for users who want Pro camera and smooth display.',specs:['256GB','Deep Purple','Verified','Stock'],badge:['VALUE','PRO']},
{id:4,cat:'iPhone',name:'iPhone 13 Pro Max',price:329,img:'products/real-product-4.jpg',desc:'Big display, strong battery and premium Apple experience at a smart price.',specs:['128GB','Graphite','Checked','Fast order'],badge:['SMART BUY']},
{id:5,cat:'AirPods',name:'AirPods Pro 2',price:194,img:'products/real-product-5.jpg',desc:'Noise cancellation, transparency mode and compact Apple audio experience.',specs:['ANC','USB‑C','New / checked','Warranty'],badge:['AUDIO']},
{id:6,cat:'AirPods',name:'AirPods Max',price:499,img:'gallery/molla-real-2.jpg',desc:'High-fidelity over-ear sound with premium Apple design.',specs:['Spatial Audio','ANC','Premium finish','On request'],badge:['PREMIUM']},
{id:7,cat:'MacBook',name:'MacBook Air M3',price:899,img:'gallery/molla-real-3.jpg',desc:'Ultra-thin laptop for study, business and creative daily work.',specs:['M3 chip','8GB/256GB','Lightweight','On request'],badge:['MAC']},
{id:8,cat:'MacBook',name:'MacBook Pro M4',price:1299,img:'gallery/molla-real-4.jpg',desc:'Powerful MacBook for creators, performance users and professionals.',specs:['M4 chip','Pro display','All-day battery','On request'],badge:['PRO']},
{id:9,cat:'Watch',name:'Apple Watch Ultra 2',price:599,img:'gallery/molla-real-5.jpg',desc:'Rugged premium Apple Watch for sport, travel and daily performance.',specs:['Titanium','GPS + Cellular','Large display','On request'],badge:['ULTRA']},
{id:10,cat:'Accessories',name:'MagSafe Premium Kit',price:49,img:'gallery/molla-real-1.jpg',desc:'Cases, chargers and daily Apple accessories selected for premium users.',specs:['Case','Cable','Charger','MagSafe'],badge:['ACCESSORIES']}
];
let active='All',cart=[];
const wa=(text)=>`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(text)}`;
function init(){document.getElementById('waTop').href=wa('Përshëndetje Molla Shop, dua të kontrolloj produktet Apple në stok.');document.getElementById('waFinal').href=wa('Përshëndetje, dua të rezervoj një produkt Apple te Molla Shop.');setTimeout(()=>loader.classList.add('hide'),550);renderCats();renderFilters();renderProducts();renderGallery();renderReels();reveal();window.addEventListener('scroll',reveal);search.addEventListener('input',renderProducts);sort.addEventListener('change',renderProducts);cartFab.onclick=()=>cart.classList.add('open');closeCart.onclick=()=>cart.classList.remove('open')}
function renderCats(){categoryGrid.innerHTML=cats.map(c=>`<article class="cat" onclick="setCat('${c[0]}')"><b>${c[0]}</b><span>${c[1]}</span><small>Explore →</small></article>`).join('')}
function renderFilters(){const fs=['All','iPhone','AirPods','MacBook','Watch','Accessories'];filters.innerHTML=fs.map(f=>`<button class="chip ${f===active?'active':''}" onclick="setCat('${f}')">${f}</button>`).join('')}
function setCat(c){active=c;renderFilters();renderProducts();document.getElementById('catalog').scrollIntoView({behavior:'smooth'})}
function data(){let q=search.value?.toLowerCase()||'';let arr=products.filter(p=>(active==='All'||p.cat===active)&&(p.name.toLowerCase().includes(q)||p.desc.toLowerCase().includes(q)||p.cat.toLowerCase().includes(q)));if(sort.value==='asc')arr.sort((a,b)=>a.price-b.price);if(sort.value==='desc')arr.sort((a,b)=>b.price-a.price);return arr}
function renderProducts(){const arr=data();productGrid.innerHTML=arr.map(p=>`<article class="product reveal"><div class="product-img"><img src="${img(p.img)}" alt="${p.name}" loading="lazy"></div><div class="badges">${p.badge.map(b=>`<span class="badge">${b}</span>`).join('')}</div><h3>${p.name}</h3><p>${p.desc}</p><div class="specs">${p.specs.map(s=>`<span>${s}</span>`).join('')}</div><div class="price-row"><b class="price">€${p.price}</b><button class="mini-btn" onclick="add(${p.id})">Reserve</button></div></article>`).join('');renderFocus(arr[0]||products[0]);reveal()}
function renderFocus(p){focusPanel.innerHTML=`<img src="${img(p.img)}" alt="${p.name}"><div><div class="badges">${p.badge.map(b=>`<span class="badge">${b}</span>`).join('')}</div><h3>${p.name}</h3><p>${p.desc}</p><ul>${p.specs.map(s=>`<li>${s}</li>`).join('')}</ul><div class="actions"><a class="btn primary" target="_blank" href="${wa(`Përshëndetje Molla Shop, dua ${p.name}. A është në stok?`)}">Ask availability</a><button class="btn ghost" onclick="add(${p.id})">Add to cart</button></div></div>`}
function add(id){const p=products.find(x=>x.id===id);cart.push(p);renderCart();cart.classList.add('open')}
function renderCart(){cartItems.innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-item"><span>${p.name}</span><b>€${p.price}</b></div>`).join(''):'<p style="color:#aaa">No products selected yet.</p>';const t=cart.reduce((s,p)=>s+p.price,0);total.textContent=`€${t}`;cartCount.textContent=cart.length;checkout.href=wa('Përshëndetje Molla Shop, dua të rezervoj:\n'+cart.map(p=>`- ${p.name} €${p.price}`).join('\n')+`\nTotali indicativ: €${t}`)}
function renderGallery(){galleryGrid.innerHTML=gallery.map((g,i)=>`<img src="${img(g)}" alt="Molla Shop visual ${i+1}" loading="lazy">`).join('')}
function renderReels(){let reelLinks=['https://www.instagram.com/_mollashop/'];reelScreen.style.backgroundImage=`url(${img('gallery/molla-real-1.jpg')})`;reelButtons.innerHTML=`<a class="btn primary" target="_blank" href="${reelLinks[0]}">Open Instagram</a><a class="btn ghost" href="#catalog">Shop products</a>`}
function reveal(){document.querySelectorAll('.reveal').forEach(el=>{if(el.getBoundingClientRect().top<innerHeight-70)el.classList.add('show')})}
init();
